# Generated by Django 3.2.7 on 2021-11-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancebill',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='maintenancebill',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
