# Generated by Django 3.2.7 on 2021-11-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211121_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
